### ISSUE TITLE
Test vdiffr

### ISSUE THREAD

**Issue by VEZY** [SticsRPacks/CroPlotR#14]
vdiffr is now active on the main branch and a comparison is triggered for every pull request.
We should make a pull request where we change the behaviour of CroPlotR and check if the action is broken as expected. 

Note on the comparison of vdiffr: the snapshots are generated using the script `tests/testthat/vdiffr/generate-snapshots.R` from the pull request. The one from the main is not used, only the code of CroPlotR changes between the two. This has the benefit that changes to the evaluation script itself are always taken into account. The potential drawback is that users that change this script have to know what they are doing, but it should be pretty rare so I think it is worth it.

**Comment by sbuis** [comment]
Doc on tests has now been added in the package
