### ISSUE TITLE
Avoid division by 0 in relative goodness-of-fit criteria

### ISSUE THREAD

**Issue by sbuis** [SticsRPacks/CroPlotR#32]
=> Remove the corresponding data from the criteria computation and warn the user

see test here-attached

[test_RME_MAPE.zip](https://github.com/SticsRPacks/CroPlotR/files/13664765/test_RME_MAPE.zip)

**Comment by cyrillemidingoyi** [comment]
[https://github.com/SticsRPacks/CroPlotR/blob/updatestats/R/generic_stats.R](url)

**Comment by sbuis** [comment]
the commit 1069ea843b236fbea5ef312f852cee04df851013 solved the issue...
